name: Trend CI/CD

on:
  push:
    branches:
      - main

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Check Docker environment
        run: |
          docker --version
          docker version

      - name: Test Docker Hub token service
        run: |
          echo "Testing Docker Hub token service..."

          curl -i \
            "https://auth.docker.io/token?service=registry.docker.io&scope=repository:arunar86/trend-app:pull,push"
