name: Trend CI/CD

on:
  push:
    branches:
      - main

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Check Docker environment
        run: |
          docker --version
          docker version

      - name: Test Docker Hub registry
        run: |
          echo "Testing Docker Hub registry..."
          curl -i https://registry-1.docker.io/v2/
